---
- name: install httpd package
  hosts: all
  become: yes
  tasks:
    - name: install httpd package
      ansible.builtin.yum:
       name: httpd
       state: present

    - name: Ensure httpd is started
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes