---
- name: Install and start httpd service
  hosts: all
  tasks:
    - name: Install httpd package
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Ensure httpd is started
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes